Repository ittybittyapps/appstoreconnect-cli, pull requests merged in 2020-04, with the labels that each got.

#59 Create Github action file swift.yml, set up github action
  .github/workflows/swift.yml
  Tests/appstoreconnect-cliTests/appstoreconnect_cliTests.swift
Labels: task

#68 Add GitHub Actions badge
  README.md
Labels: documentation

#73 Improve bundle-ids commands
  Sources/AppStoreConnectCLI/Commands/BundleIds/DeleteBundleIdCommand.swift
  Sources/AppStoreConnectCLI/Commands/BundleIds/HTTPClient+BundleId.swift
  Sources/AppStoreConnectCLI/Commands/BundleIds/ListBundleIdsCommand.swift
  Sources/AppStoreConnectCLI/Commands/BundleIds/ModifyBundleIdCommand.swift
  Sources/AppStoreConnectCLI/Commands/BundleIds/ReadBundleIdCommand.swift
  Sources/AppStoreConnectCLI/Commands/BundleIds/RegisterBundleIdCommand.swift
  Sources/AppStoreConnectCLI/Helpers/Publisher+Helpers.swift
  Sources/AppStoreConnectCLI/Model/API/BundleIdPlatform+Init.swift
  Sources/AppStoreConnectCLI/Model/BundleId.swift
  Sources/AppStoreConnectCLI/Readers and Renderers/Renderers.swift
Labels: enhancement

#76 Update packages to latest versions
  Package.resolved
Labels: enhancement

#75 Add and update device commands
  README.md
  Sources/AppStoreConnectCLI/Commands/BundleIds/DeleteBundleIdCommand.swift
  Sources/AppStoreConnectCLI/Commands/BundleIds/HTTPClient+BundleId.swift
  Sources/AppStoreConnectCLI/Commands/BundleIds/ModifyBundleIdCommand.swift
  Sources/AppStoreConnectCLI/Commands/BundleIds/ReadBundleIdCommand.swift
  Sources/AppStoreConnectCLI/Commands/Devices/DevicesCommand.swift
  Sources/AppStoreConnectCLI/Commands/Devices/HTTPClient+DeviceId.swift
  Sources/AppStoreConnectCLI/Commands/Devices/ListDevicesCommand.swift
  Sources/AppStoreConnectCLI/Commands/Devices/ModifyDeviceCommand.swift
  Sources/AppStoreConnectCLI/Commands/Devices/ReadDeviceInfoCommand.swift
  Sources/AppStoreConnectCLI/Commands/Devices/RegisterDeviceCommand.swift
  Sources/AppStoreConnectCLI/Model/API/BundleIdPlatform+ExpressibleByArgument.swift
  Sources/AppStoreConnectCLI/Model/API/DeviceStatus+ExpressibleByArgument.swift
  Sources/AppStoreConnectCLI/Model/API/Devices.Sort+ExpressibleByArgument.swift
  Sources/AppStoreConnectCLI/Model/API/Platform+Helpers.swift
  Sources/AppStoreConnectCLI/Model/Device.swift
Labels: enhancement

#58 Implement ListBetaTestersCommand
  Package.resolved
  Package.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/CreateBetaTesterCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/DeleteBetaTesterCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/HTTPClient+BetaTester.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/ListBetaTesterByBuildsCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/ListBetaTestersCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/TestFlightBetaTestersCommand.swift
  Sources/AppStoreConnectCLI/Model/App.swift
  Sources/AppStoreConnectCLI/Model/BetaGroup.swift
  Sources/AppStoreConnectCLI/Model/BetaTester.swift
  Sources/AppStoreConnectCLI/Model/User.swift
Labels: enhancement

#80 Extract API calls out into APIOperation objects
  Sources/AppStoreConnectCLI/Commands/BundleIds/DeleteBundleIdCommand.swift
  Sources/AppStoreConnectCLI/Commands/BundleIds/HTTPClient+BundleId.swift
  Sources/AppStoreConnectCLI/Commands/BundleIds/ListBundleIdsCommand.swift
  Sources/AppStoreConnectCLI/Commands/BundleIds/ModifyBundleIdCommand.swift
  Sources/AppStoreConnectCLI/Commands/BundleIds/ReadBundleIdCommand.swift
  Sources/AppStoreConnectCLI/Commands/BundleIds/RegisterBundleIdCommand.swift
  Sources/AppStoreConnectCLI/Commands/CommonParsableCommand.swift
  Sources/AppStoreConnectCLI/Commands/Devices/HTTPClient+DeviceId.swift
  Sources/AppStoreConnectCLI/Commands/Devices/ListDevicesCommand.swift
  Sources/AppStoreConnectCLI/Commands/Devices/ModifyDeviceCommand.swift
  Sources/AppStoreConnectCLI/Commands/Devices/ReadDeviceInfoCommand.swift
  Sources/AppStoreConnectCLI/Commands/Devices/RegisterDeviceCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/Apps/ListAppsCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/CreateBetaTesterCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/DeleteBetaTesterCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/HTTPClient+BetaTester.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/ListBetaTesterByBuildsCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/ListBetaTestersCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/Builds/GetBuildInfoCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/Builds/ListBuildsCommand.swift
  Sources/AppStoreConnectCLI/Commands/Users/GetUserInfoCommand.swift
  Sources/AppStoreConnectCLI/Commands/Users/Invitations/CancelUserInvitationsCommand.swift
  Sources/AppStoreConnectCLI/Commands/Users/Invitations/InviteUserCommand.swift
  Sources/AppStoreConnectCLI/Commands/Users/Invitations/ListUserInvitationsCommand.swift
  Sources/AppStoreConnectCLI/Commands/Users/ListUsersCommand.swift
  Sources/AppStoreConnectCLI/Commands/Users/SyncUsersCommand.swift
  Sources/AppStoreConnectCLI/Helpers/Collection+Helpers.swift
  Sources/AppStoreConnectCLI/Helpers/HTTPClient+Helpers.swift
  Sources/AppStoreConnectCLI/Model/App.swift
  Sources/AppStoreConnectCLI/Model/BetaGroup.swift
  Sources/AppStoreConnectCLI/Model/User.swift
  Sources/AppStoreConnectCLI/Model/UserInvitation.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/HTTPClient.swift
  Sources/AppStoreConnectCLI/Services/Operations/APIOperation.swift
  Sources/AppStoreConnectCLI/Services/Operations/GetUserInfoOperation.swift
  Sources/AppStoreConnectCLI/Services/Operations/ListUsersOperation.swift
  Sources/AppStoreConnectCLI/Services/Options/GetUserInfoOptions.swift
  Sources/AppStoreConnectCLI/Services/Options/ListUserOptions.swift
  Tests/appstoreconnect-cliTests/Operations/GetUserInfoOperationTests.swift
Labels: enhancement

#116 Implement CreateCertificateCommand
  Sources/AppStoreConnectCLI/Commands/Certificates/CertificatesCommand.swift
  Sources/AppStoreConnectCLI/Commands/Certificates/CreateCertificateCommand.swift
  Sources/AppStoreConnectCLI/Model/API/CertificateType+ExpressibleByArgument.swift
  Sources/AppStoreConnectCLI/Model/Certificate.swift
Labels: enhancement

#83 Add Makefile for brew formula
  Makefile
Labels: enhancement

#119 Update README homebrew instructions
  README.md
Labels: documentation

#117 Use Operations in CreateCertificateCommand
  Sources/AppStoreConnectCLI/Commands/Certificates/CreateCertificateCommand.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/CreateCertificateOperation.swift
  Sources/AppStoreConnectCLI/Services/Options/CreateCertificateOptions.swift
  Tests/appstoreconnect-cliTests/Operations/CreateCertificateOperationTests.swift
Labels: enhancement

#89 Add notFound Error for function deviceUDIDResourceId
  Sources/AppStoreConnectCLI/Commands/Devices/HTTPClient+DeviceId.swift
Labels: bug

#118 Implement ListDownloadCertificate Command
  Sources/AppStoreConnectCLI/Commands/Certificates/CertificatesCommand.swift
  Sources/AppStoreConnectCLI/Commands/Certificates/ListDownloadCertificates.swift
  Sources/AppStoreConnectCLI/Model/API/Certificates.Sort+ExpressibleByArgument.swift
  Sources/AppStoreConnectCLI/Model/Certificate.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/ListCertificatesOpertaion.swift
  Sources/AppStoreConnectCLI/Services/Options/ListCertificatesOptions.swift
  Tests/appstoreconnect-cliTests/Operations/ListCertificateOperations.swift
Labels: enhancement

#79 Profile Commands
  Package.resolved
  Package.swift
  README.md
  Sources/AppStoreConnectCLI/Commands/BundleIds/AppStoreConnectService+BundleId.swift
  Sources/AppStoreConnectCLI/Commands/Devices/AppStoreConnectService+DeviceId.swift
  Sources/AppStoreConnectCLI/Commands/Profiles/AppStoreConnectService+ProfileId.swift
  Sources/AppStoreConnectCLI/Commands/Profiles/CreateProfileCommand.swift
  Sources/AppStoreConnectCLI/Commands/Profiles/DeleteProfileCommand.swift
  Sources/AppStoreConnectCLI/Commands/Profiles/ListProfilesCommand.swift
  Sources/AppStoreConnectCLI/Commands/Profiles/ProfilesCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/AppStoreConnectService+BetaTester.swift
  Sources/AppStoreConnectCLI/Helpers/AppStoreConnectService+Helpers.swift
  Sources/AppStoreConnectCLI/Model/API/ProfileState+ExpressibleByArgument.swift
  Sources/AppStoreConnectCLI/Model/API/ProfileType+ExpressibleByArgument.swift
  Sources/AppStoreConnectCLI/Model/API/Profiles.Sort+ExpressibleByArgument.swift
  Sources/AppStoreConnectCLI/Model/Profile.swift
Labels: enhancement

#81 Testflight/Implement invite beta tester command
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/CreateBetaTesterCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/DeleteBetaTesterCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/InviteBetaTesterCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/ListBetaTestersCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/TestFlightBetaTestersCommand.swift
  Sources/AppStoreConnectCLI/Model/App.swift
  Sources/AppStoreConnectCLI/Model/BetaGroup.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/APIOperation.swift
  Sources/AppStoreConnectCLI/Services/Operations/CreateBetaGroupOperation.swift
  Sources/AppStoreConnectCLI/Services/Operations/GetAppsOperation.swift
  Sources/AppStoreConnectCLI/Services/Operations/GetBetaTesterInfoOperation.swift
  Sources/AppStoreConnectCLI/Services/Operations/InviteTesterOperation.swift
  Sources/AppStoreConnectCLI/Services/Options/GetBetaTesterInfoOptions.swift
  Sources/AppStoreConnectCLI/Services/Options/InviteBetaTesterOptions.swift
  Tests/appstoreconnect-cliTests/Operations/GetBetaTesterInfoOperationTests.swift
Labels: enhancement
