Repository ittybittyapps/appstoreconnect-cli, pull requests merged in 2020-09, with the labels that each got.

#223 List, read, create, delete, update Beta Build Localizations
  Sources/AppStoreConnectCLI/Arguments/BuildArguments.swift
  Sources/AppStoreConnectCLI/Arguments/BuildLocalizationInputArguments.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/Builds/Localizations/CreateBuildLocalizationsCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/Builds/Localizations/DeleteBuildLocalizationsCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/Builds/Localizations/ListBuildLocalizationsCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/Builds/Localizations/LocalizationsCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/Builds/Localizations/ReadBuildLocalizationCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/Builds/Localizations/UpdateBuildLocalizationsCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/Builds/TestFlightBuildsCommand.swift
  Sources/AppStoreConnectCLI/Helpers/String+Helpers.swift
  Sources/AppStoreConnectCLI/Model/BuildLocalization.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/CreateBuildLocalizationOperation.swift
  Sources/AppStoreConnectCLI/Services/Operations/DeleteBuildLocalizationOperation.swift
  Sources/AppStoreConnectCLI/Services/Operations/ListBuildLocalizationOperation.swift
  Sources/AppStoreConnectCLI/Services/Operations/ReadBuildLocalizationOperation.swift
  Sources/AppStoreConnectCLI/Services/Operations/UpdateBuildLocalizationOperation.swift
  Sources/Model/BuildLocalization.swift
Labels: enhancement

#216 Implement ReadProfileCommand, also add filter profile by ID feature to ListProfilesCommand
  Sources/AppStoreConnectCLI/Commands/Profiles/ListProfilesCommand.swift
  Sources/AppStoreConnectCLI/Commands/Profiles/ProfilesCommand.swift
  Sources/AppStoreConnectCLI/Commands/Profiles/ReadProfileCommand.swift
  Sources/AppStoreConnectCLI/Model/Profile.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/ListProfilesOperation.swift
  Sources/AppStoreConnectCLI/Services/Operations/ReadProfileOperation.swift
  Sources/Model/Profile.swift
Labels: enhancement, regression

#217 Add a ListProfilesByBundleId command
  Sources/AppStoreConnectCLI/Commands/Profiles/ListProfilesByBundleIdCommand.swift
  Sources/AppStoreConnectCLI/Commands/Profiles/ProfilesCommand.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/ListProfilesByBundleIdOperation.swift
Labels: enhancement

#235 Change ListProfilesByBundleIdCommand to use fuzzy search
  Package.resolved
  Sources/AppStoreConnectCLI/Commands/Profiles/ListProfilesByBundleIdCommand.swift
  Sources/AppStoreConnectCLI/Model/API/Sales.Filter+ExpressibleByArgument.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
Labels: regression
