Repository ittybittyapps/appstoreconnect-cli, pull requests merged in 2020-05, with the labels that each got.

#123 Implement List Beta Groups
  Sources/AppStoreConnectCLI/AppStoreConnectCLI.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaGroups/BetaGroupCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaGroups/CreateBetaGroupCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaGroups/ListBetaGroupsCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/TestFlightCommand.swift
  Sources/AppStoreConnectCLI/Model/API/ExtendedBetaGroup.swift
  Sources/AppStoreConnectCLI/Model/App.swift
  Sources/AppStoreConnectCLI/Model/BetaGroup.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/CreateBetaGroupOperation.swift
  Sources/AppStoreConnectCLI/Services/Operations/GetAppsOperation.swift
  Sources/AppStoreConnectCLI/Services/Operations/ListBetaGroupsOperation.swift
  Sources/AppStoreConnectCLI/Services/Options/CreateBetaGroupOptions.swift
  Sources/AppStoreConnectCLI/Services/Options/GetAppsOptions.swift
  Tests/appstoreconnect-cliTests/Operations/CreateBetaGroupOperationTests.swift
  Tests/appstoreconnect-cliTests/Operations/ListBetaGroupsOperationTests.swift
Labels: enhancement

#82 TestFlight/Implement get tester information command
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/GetBetaTesterInfoCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/InviteBetaTesterCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/ListBetaTesterByBuildsCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/ListBetaTestersCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/TestFlightBetaTestersCommand.swift
  Sources/AppStoreConnectCLI/Model/BetaTester.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/GetBetaTesterInfoOperation.swift
  Sources/AppStoreConnectCLI/Services/Operations/GetBetaTesterOperation.swift
  Sources/AppStoreConnectCLI/Services/Operations/InviteTesterOperation.swift
  Sources/AppStoreConnectCLI/Services/Options/GetBetaTesterInfoOptions.swift
  Tests/appstoreconnect-cliTests/Operations/GetBetaTesterInfoOperationTests.swift
Labels: enhancement

#122 Implement Read download certificate Command
  Sources/AppStoreConnectCLI/Commands/Certificates/CertificatesCommand.swift
  Sources/AppStoreConnectCLI/Commands/Certificates/ListCertificatesCommand.swift
  Sources/AppStoreConnectCLI/Commands/Certificates/ReadCertificateCommand.swift
  Sources/AppStoreConnectCLI/Model/Errors/Certificates.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/ReadCertificateOperation.swift
  Tests/appstoreconnect-cliTests/Mockup/Certificates.swift
  Tests/appstoreconnect-cliTests/Operations/CreateCertificateOperationTests.swift
  Tests/appstoreconnect-cliTests/Operations/ListCertificateOperations.swift
  Tests/appstoreconnect-cliTests/Operations/ReadCertificateOperationTests.swift
Labels: enhancement

#129 Implement Delete Beta Testers Command
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/DeleteBetaTesterCommand.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/DeleteBetaTesterOperation.swift
Labels: enhancement

#124 Implement Revoke Certificates Command
  Sources/AppStoreConnectCLI/Commands/Certificates/CertificatesCommand.swift
  Sources/AppStoreConnectCLI/Commands/Certificates/RevokeCertificatesCommand.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/ReadCertificateOperation.swift
  Sources/AppStoreConnectCLI/Services/Operations/RevokeCertificateOperation.swift
  Tests/appstoreconnect-cliTests/Operations/ReadCertificateOperationTests.swift
Labels: enhancement

#134 Rename GetBetaTesterInfoCommand
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/ReadBetaTesterCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/TestFlightBetaTestersCommand.swift
Labels: enhancement

#133 Implement ListBetaTesterCommand
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/ListBetaTestersCommand.swift
  Sources/AppStoreConnectCLI/Model/API/BetaInviteType+ExpressibleByArgument.swift
  Sources/AppStoreConnectCLI/Model/API/ListBetaTesters.Sort+ExpressibleByArgument.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/ListBetaTestersOperation.swift
Labels: enhancement

#140 Implement read app command
  Sources/AppStoreConnectCLI/Commands/TestFlight/Apps/ReadAppCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/Apps/TestFlightAppsCommand.swift
  Sources/AppStoreConnectCLI/Model/App.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/ReadAppOperation.swift
Labels: enhancement

#138 Implement RemoveBetaTester(s)FromGroup(s)
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaGroups/BetaGroupCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaGroups/RemoveTestersFromGroupCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/RemoveTesterFromGroupsCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/TestFlightBetaTestersCommand.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/RemoveTesterOperation.swift
Labels: enhancement

#142 Implement Remove build from groups command
  Sources/AppStoreConnectCLI/Commands/TestFlight/Builds/RemoveGroupsFromBuildCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/Builds/TestFlightBuildsCommand.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/RemoveBuildFromGroupsOperation.swift
Labels: enhancement

#145 Use enum and identifier in GetBetaTesterOperation Options
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/GetBetaTesterOperation.swift
Labels: regression

#141 Add pagination for List Build Command
  Sources/AppStoreConnectCLI/Services/EndpointRequestor.swift
  Sources/AppStoreConnectCLI/Services/Operations/ListBuildsOperation.swift
Labels: bug

#144 Implement Add tester's' to group's' Command
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaGroups/AddTestersToGroupCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaGroups/BetaGroupCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/AddTesterToGroupsCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/TestFlightBetaTestersCommand.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/AddTesterToGroupOperation.swift
Labels: enhancement

#121 Add ListPreReleaseVersionsCommand
  .swiftpm/xcode/xcshareddata/xcschemes/appstoreconnect-cli.xcscheme
  Package.resolved
  README.md
  Sources/AppStoreConnectCLI/Commands/TestFlight/PreReleaseVersion/ListPreReleaseVersionsCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/PreReleaseVersion/TestFlightPreReleaseVersionCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/TestFlightCommand.swift
  Sources/AppStoreConnectCLI/Model/API/ListPrereleaseVersions.Filter.BuildsProcessingState+ExpressibleByArgument.swift
  Sources/AppStoreConnectCLI/Model/API/ListPrereleaseVersions.Sort+ExpressibleByArgument.swift
  Sources/AppStoreConnectCLI/Model/API/Platform+ExpressibleByArgument.swift
  Sources/AppStoreConnectCLI/Model/PrereleaseVersion.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/ListPreReleaseVersionsOperation.swift
  Tests/appstoreconnect-cliTests/Operations/ListPreReleaseVersionsOperationTests.swift
Labels: enhancement

#149 Extract App and BetaGroup model into Model module
  .swiftpm/xcode/xcshareddata/xcschemes/appstoreconnect-cli.xcscheme
  Package.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/Apps/ListAppsCommand.swift
  Sources/AppStoreConnectCLI/Model/App.swift
  Sources/AppStoreConnectCLI/Model/BetaGroup.swift
  Sources/AppStoreConnectCLI/Model/Build.swift
  Sources/AppStoreConnectCLI/Model/PrereleaseVersion.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/Model/App.swift
  Sources/Model/BetaGroup.swift
Labels: task

#143 Implement Add build to groups command
  Sources/AppStoreConnectCLI/Arguments/BuildArguments.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/Builds/AddGroupsToBuildCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/Builds/ExpireBuildCommand.swift
  Sources/AppStoreConnectCLI/Commands/TestFlight/Builds/TestFlightBuildsCommand.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/AddGroupsToBuildOperation.swift
  Sources/AppStoreConnectCLI/Services/Operations/ListBetaGroupsOperation.swift
Labels: enhancement

#153 Improve list builds command
  Sources/AppStoreConnectCLI/Commands/TestFlight/Builds/ListBuildsCommand.swift
  Sources/AppStoreConnectCLI/Model/Build.swift
Labels: enhancement

#157 Add pagination for ListBetaTestersOperation
  Sources/AppStoreConnectCLI/Services/Operations/ListBetaTestersOperation.swift
Labels: bug, regression

#154 Tweak Invite Tester Operation, add group identifer
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaTesters/InviteBetaTesterCommand.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/InviteTesterOperation.swift
  Sources/AppStoreConnectCLI/Services/Options/InviteBetaTesterOptions.swift
Labels: regression

#162 Add read CSV support for File reader
  Sources/AppStoreConnectCLI/Readers and Renderers/Formats.swift
  Sources/AppStoreConnectCLI/Readers and Renderers/Readers.swift
Labels: enhancement

#172 Bug/Fix list beta tester group name not unique
  Sources/AppStoreConnectCLI/Model/BetaGroup.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/GetBetaGroupOperation.swift
Labels: bug

#174 Add exclude internal group option to List Beta Group Command
  Sources/AppStoreConnectCLI/Commands/TestFlight/BetaGroups/ListBetaGroupsCommand.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/ListBetaGroupsOperation.swift
Labels: enhancement, regression

#178 Move Options into Operations
  Sources/AppStoreConnectCLI/Commands/Certificates/CreateCertificateCommand.swift
  Sources/AppStoreConnectCLI/Commands/Certificates/ListCertificatesCommand.swift
  Sources/AppStoreConnectCLI/Commands/Users/GetUserInfoCommand.swift
  Sources/AppStoreConnectCLI/Commands/Users/ListUsersCommand.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/CreateCertificateOperation.swift
  Sources/AppStoreConnectCLI/Services/Operations/GetUserInfoOperation.swift
  Sources/AppStoreConnectCLI/Services/Operations/ListCertificatesOpertaion.swift
  Sources/AppStoreConnectCLI/Services/Operations/ListUsersOperation.swift
  Sources/AppStoreConnectCLI/Services/Options/CreateCertificateOptions.swift
  Sources/AppStoreConnectCLI/Services/Options/GetUserInfoOptions.swift
  Sources/AppStoreConnectCLI/Services/Options/ListCertificatesOptions.swift
  Sources/AppStoreConnectCLI/Services/Options/ListUserOptions.swift
  Tests/appstoreconnect-cliTests/Operations/CreateCertificateOperationTests.swift
  Tests/appstoreconnect-cliTests/Operations/GetUserInfoOperationTests.swift
  Tests/appstoreconnect-cliTests/Operations/ListCertificateOperations.swift
Labels: regression
