Repository ittybittyapps/appstoreconnect-cli, pull requests merged in 2020-06, with the labels that each got.

#181 Update List Devices Command to use Operation
  Sources/AppStoreConnectCLI/Commands/Devices/ListDevicesCommand.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/ListDevicesOperation.swift
Labels: regression

#165 Bug/add pagination to operations
  Sources/AppStoreConnectCLI/Helpers/Collection+Helpers.swift
  Sources/AppStoreConnectCLI/Services/Operations/ListAppsOperation.swift
  Sources/AppStoreConnectCLI/Services/Operations/ListBundleIdsOperation.swift
  Sources/AppStoreConnectCLI/Services/Operations/ListCertificatesOpertaion.swift
  Sources/AppStoreConnectCLI/Services/Operations/ListPreReleaseVersionsOperation.swift
  Sources/AppStoreConnectCLI/Services/Operations/ListUsersOperation.swift
  Tests/appstoreconnect-cliTests/Operations/ListCertificateOperations.swift
Labels: bug

#182 Update List Profiles Command to use Operation
  Sources/AppStoreConnectCLI/Commands/Profiles/ListProfilesCommand.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/ListDevicesOperation.swift
  Sources/AppStoreConnectCLI/Services/Operations/ListProfilesOperation.swift
Labels: regression

#184 Update List User Invitations Command to use Operation
  Sources/AppStoreConnectCLI/Commands/Users/Invitations/ListUserInvitationsCommand.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/ListUserInvitationsOperation.swift
Labels: regression

#188 Remove TODOs from README
  README.md
Labels: documentation

#186 Implement Enable bundleId Capability Command
  Sources/AppStoreConnectCLI/AppStoreConnectCLI.swift
  Sources/AppStoreConnectCLI/Commands/Capability/CapabilityCommand.swift
  Sources/AppStoreConnectCLI/Commands/Capability/EnableBundleIdCapability.swift
  Sources/AppStoreConnectCLI/Model/API/CapabilityType+ExpressibleByArgument.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/EnableBundleIdCapabilityOperation.swift
  Sources/AppStoreConnectCLI/Services/Operations/ReadBundleIdOperation.swift
Labels: enhancement

#187 Introduce File System module
  Package.swift
  Sources/AppStoreConnectCLI/Commands/Certificates/ListCertificatesCommand.swift
  Sources/AppStoreConnectCLI/Commands/Certificates/ReadCertificateCommand.swift
  Sources/AppStoreConnectCLI/Commands/Profiles/ListProfilesCommand.swift
  Sources/AppStoreConnectCLI/Commands/Users/SyncUsersCommand.swift
  Sources/AppStoreConnectCLI/Readers and Renderers/Formats.swift
  Sources/FileSystem/Certificates/CertificateProcessor.swift
  Sources/FileSystem/Formats.swift
  Sources/FileSystem/Profile/ProfileProcessor.swift
  Sources/FileSystem/Readers.swift
  Sources/FileSystem/ResourceProcessor.swift
Labels: enhancement

#190 Introduce release drafter
  .github/release-drafter.yml
  .github/workflows/draft-release.yml
Labels: task

#196 Add paging support to ListProfilesCommand
  .swiftpm/xcode/xcshareddata/xcschemes/appstoreconnect-cli.xcscheme
  Package.resolved
  Sources/AppStoreConnectCLI/Services/Operations/ListProfilesOperation.swift
Labels: bug

#194 Implement DownloadSalesAndTrendsReportsCommand
  Sources/AppStoreConnectCLI/Commands/Reports/DownloadSalesAndTrendsReportsCommand.swift
  Sources/AppStoreConnectCLI/Commands/Reports/ReportsCommand.swift
  Sources/AppStoreConnectCLI/Model/API/Sales.Filter+ExpressibleByArgument.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/DownloadSalesOperation.swift
  Sources/FileSystem/Reports/ReportProcessor.swift
Labels: enhancement

#195 Implement DownloadFinancialReportsCommand
  README.md
  Sources/AppStoreConnectCLI/Commands/Reports/DownloadFinancialReportsCommand.swift
  Sources/AppStoreConnectCLI/Commands/Reports/ReportsCommand.swift
  Sources/AppStoreConnectCLI/Model/API/RegionCode+ExpressibleByArgument.swift
  Sources/AppStoreConnectCLI/Services/AppStoreConnectService.swift
  Sources/AppStoreConnectCLI/Services/Operations/DownloadFinanceReportsOperation.swift
Labels: enhancement

#197 Enable limit in list bundle ids operation
  Sources/AppStoreConnectCLI/Services/Operations/ListBundleIdsOperation.swift
Labels: bug
